### PR TITLE
Sample package-lock fixes & migration to vite for react samples

### PR DESCRIPTION
**Pull request by ryanbliss**
In this pull request, I've addressed numerous issues with the samples that stem from package-lock files that included references to private npm feeds as well as dependencies that aren't actually in package.json files. Here are the changes included in this PR:

1. Deleted all package-lock files from each sample
2. Deleted lerna-package-lock from root directory
3. Ran fresh installs from each to generate new package-lock files
4. Resolved webpack 5 issues for buffer references used in Fluid Framework
5. To fix above for React samples, I migrated React samples to Vite, which was not only a simpler solution but also improves build times considerably
6. Added eslint dependencies and .eslintrc files to each sample to resolve issues when running samples from each individual sample, which incidentally also runtime lint errors which were previously uncaught. Those issues have now been fixed.
7. Minor bug fixes / console error resolutions that I found when testing samples.

To make sure this doesn't cause any regressions, I tested each sample using npm run start and npm run build, both in each individual sample and from the root directory. Each appears to be working as expected!

### CODE REVIEW

**Review by corinagum — APPROVED** [review]
LGTM ~

**Review by Stevenic — APPROVED** [review]

**Comment by pradeepananth** [comment]
Are the samples, especially react-media-template, tested in Teams?

**Review by pradeepananth — CHANGES_REQUESTED** [review]
Are the samples, especially react-media-template, tested in Teams?
Please share any screen shot of sample running in Teams.

**Comment by ryanbliss** [comment]
> Are the samples, especially react-media-template, tested in Teams? Please share any screen shot of sample running in Teams.

Sure, I just tested in Teams with Ngrok, and actually found a quirk with how ngrok and vite work. I had to add a new start-https command which basically lets Vite work with https during hot reloading. For localhost, start works just fine. This has no impact on blob deployments. I've also updated the README with this info and will investigate ways to remove this requirement. _Note:_ this only impacts the React samples.

image

**Review by pradeepananth — APPROVED** [review]

**Pull request merged**
